### PR TITLE
1 improve footer ui

### PR DESCRIPTION
**Pull request by kkotelczuk**
According to issue #1 
footer data has been changed

### CODE REVIEW

**Comment by kkotelczuk** [comment]
Ofcourse, here it is: 
zrzut ekranu 2018-10-11 o 12 28 03

**Comment by kindacoder** [comment]
> Ofcourse, here it is:
> zrzut ekranu 2018-10-11 o 12 28 03

Thanks :+1:  Please add a file named **contributors.md** and include your name in the contributors list .

**Comment by kkotelczuk** [comment]
Done :)

**Comment by kindacoder** [comment]
Are you interested in contributing to this project ? Need some changes internally :label:

**Comment by kindacoder** [comment]
> Are you interested in contributing to this project ? Need some changes internally

@kkotelczuk

**Comment by kkotelczuk** [comment]
ATM I don't have enough time. I used your repo for Hacktoberfest event proposes, to show other participants how to make firs PR.

**Comment by kindacoder** [comment]
> ATM I don't have enough time. I used your repo for Hacktoberfest event proposes, to show other participants how to make firs PR.

oh. ok no problem Thanks :+1:

**Pull request merged**
